version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: List Static Website Files
          command: |
            echo "Listing website files..."
            ls -al

  build_docker_image:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker Image
          command: |
            echo "Building Docker image..."
            docker build -t $DOCKER_USERNAME/static-website:latest .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            echo "Pushing image to Docker Hub..."
            docker push $DOCKER_USERNAME/static-website:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image
